=== sebastian89n/code-learning-hub/java/jaxp/src/main/resources/students.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" type="student" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="student">
        <xs:sequence>
            <xs:element name="firstname" type="xs:string"/>
            <xs:element name="lastname" type="xs:string"/>
            <xs:element name="birthdate" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:integer" use="required"/>
    </xs:complexType>
</xs:schema>

=== sebastian89n/code-learning-hub/java/jaxp/src/main/resources/students.xml
<?xml version="1.0" encoding="UTF-8" ?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="students.xsd">
    <student id="59">
        <firstname>Danni</firstname>
        <lastname>Davis</lastname>
        <birthdate>1986-05-10</birthdate>
    </student>

    <student id="35">
        <firstname>Hester</firstname>
        <lastname>Benji</lastname>
        <birthdate>1989-01-27</birthdate>
    </student>

    <student id="391">
        <firstname>Kylan</firstname>
        <lastname>Sydney</lastname>
        <birthdate>1991-05-10</birthdate>
    </student>
</students>
